from .report_generation import create_report_generation_tab, register_report_generation_callbacks
from .analytics import create_analytics_tab, register_analytics_callbacks
from .image_viewer import create_image_viewer_tab, register_image_viewer_callbacks
